name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Azure Kubernetes CLI
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: psp-aks-test
        resource-group: psp-test  

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login pspregistry1272.azurecr.io -u pspregistry1272 --password-stdin
      env:
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -t pspregistry1272.azurecr.io/my-python-app:latest .

    - name: Push Docker image
      run: |
        docker push pspregistry1272.azurecr.io/my-python-app:latest

    - name: Deploy to AKS
      run: kubectl apply -f deployment.yml -f service.yml
